### ISSUE TITLE
Rendered result of Filament-based SceneWidget is blury, how can I export camera settings of SceneWidget and use which to render in Visualizer

### ISSUE THREAD

**Issue by Leerw** [intel-isl/Open3D#3778] opened 2021-07-21 10:07 UTC
**IMPORTANT: Please use the following template to report the bug.**

Before submitting:

1. Similar issue: [#2946: Visualization blur when utilizing SceneWidget as opposed to Visualizer](https://github.com/intel-isl/Open3D/issues/2946).

**Describe the bug**
Rendered result of Filament-based SceneWidget is blury, how can I export camera settings of SceneWidget and use which to render in Visualizer

**To Reproduce**
https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/multiple-windows.py

just use the example script and render a snapshot, the rendered result is blury.

**Expected behavior**
The rendered image should be clear as that produced from o3d.visualization.draw_geometries()

**Screenshots**

**Environment (please complete the following information):**

- Operating system: Windows 10 64-bit
- Python version: Python3.8
- Open3D version: 0.13.0
- Is this remote workstation?: no
- How did you install Open3D?: pip
- Compiler version (if built from source): (e.g. gcc 7.5, clang 7.0)

**Additional context**
If we cannot boost the rendering quality, how can I export camera settings of SceneWidget and use which to render in Visualizer conveniently?

**Comment by Leerw** [comment] 2021-07-21 10:08
@prewettg @errissa @griegler

**Comment by ssheorey** [comment] 2021-07-21 22:33
Duplicate of #2946 

@Leerw thanks for reporting this and commenting on #2946 . Extra data points help.
But please don't open duplicate issues. Managing them become difficult and increases time needed to resolve them.

**Comment by ssheorey** [comment] 2021-07-21 22:33
Duplicate of #2946

**Closed** 2021-07-22 12:34 UTC
