### ISSUE TITLE
ConvertFromPinholeCameraParameters() failed

### ISSUE THREAD

**Issue by zy871125746** [intel-isl/Open3D#834] opened 2019-02-18 06:05 UTC
**Describe the bug**
Hi, I tried to change the view of camera in open3d with a realsense intrinsic parameter. And got failed message "ConvertFromPinholeCameraParameters() failed because window height and width do not match" caused by
https://github.com/IntelVCL/Open3D/blob/21022d6bf2f9fbc392fd74db5248b5a05d4c7194/src/Visualization/Visualizer/ViewControl.cpp#L159-L162

The realsense intrinsic matrix is 
[618.7043457, 0.,                     332.84701538,
 0.,                   618.79547119, 232.08154297,
 0.,                    0.,                    1.]

Does the ConvertFromPinholeCameraParameters function can only  set up a virtual camera ?

**Environment :**
 - OS:Ubuntu 16.04
 - Python version: 3.6.6
 - Open3D version:0.5.0.0
 - Is this remote workstation?:  no
 - How did you install Open3D?: pip

**Comment by syncle** [comment] 2019-02-20 08:29
This is duplicate of #596. @qianyizh - how can we upgrade the visualizer to accept arbitrary camera intrinsic matrix?

**Comment by qianyizh** [comment] 2019-02-20 18:45
The underlying problem is that the conventional OpenGL camera control is only compatible with very standard camera model. On extrinsic side, you can control rotation, translation, and scale. On intrinsic side, it only supports field of view (controlled with ``[`` and ``]``), which basically only allows you to change focal length x and focal length y simultaneously. The focal center is assumed to be the center of the screen and the skew is assumed to be 0. Also, Open3D implements an orthogonal camera once field of view is set to 0. But this camera models is only a conceptual camera and does not fit with any physical pinhole camera.

As a compromise, Visualizer has a strong limitation on pinhole camera models that can be converted into ViewControl.

If we want to support arbitrary intrinsic matrix, we should implement a customized ViewControl / Visualizer which disables manual editing of focal length but can support conversion from an arbitrary intrinsic matrix.

**Comment by saulzar** [comment] 2020-01-05 08:45
To clarify - this is not an OpenGL restriction though is it? But restriction of the interface Open3D is providing?

**Comment by saulzar** [comment] 2020-01-05 09:06
Could it just be a separate mode  (e.g. similar to Perspective or Orthogonal)  (where maybe the view is fixed?), where you can allow any kind of intrinsic camera matrix?

The transforms are described quite well here:
http://ksimek.github.io/2013/06/03/calibrated_cameras_in_opengl/

**Comment by germanros1987** [comment] 2020-07-27 23:40
@errissa let's take care of this right after we roll out our scriptable rendering API.

**Comment by zapaishchykova** [comment] 2020-08-31 21:48
following!

**Comment by Salingo** [comment] 2020-09-17 01:50
Same issue, following

**Comment by theNded** [comment] 2020-12-31 16:02
Resolved in #2564. Closed for now.

**Closed by theNded** 2020-12-31 16:02 UTC
Labels: possible bug
