### ISSUE TITLE
Invalid Pointer

### ISSUE THREAD

**Issue by Zumbalamambo** [intel-isl/Open3D#3120] opened 2021-03-04 22:21 UTC
I tried the reconstruction pipeline as follows,

`python ../pipelines/color_map_optimization_for_reconstruction_system.py  --config config/realsense.json
`

but it throws the following error,

```
Extracting frames from RGBD video file
free(): invalid pointer
Aborted (core dumped)
```

how can I sort it out?

**Comment by ssheorey** [comment] 2021-03-05 18:35
Hi @Zumbalamambo please fill out your environment and Open3D information according to the bug reporting template. This may be an issue that's already been fixed.

Can you run this Python unit test and report it's results?
First, comment out line 41 in `python/test/t/io/test_realsense.py`

`# @pytest.mark.skip(reason="Hangs in Github Actions, but succeeds locally")`

Then run (You'll need `pytest` installed):
`python -m pytest -svv -rs ../python/test/t/io/test_realsense.py`

**Comment by ssheorey** [comment] 2021-03-11 23:36
This is likely the same as #2837. If working only with Python, please try the latest development wheel.

**Comment by ssheorey** [comment] 2021-03-11 23:44
Duplicate of #2837

**Comment by ssheorey** [comment] 2021-03-11 23:45
@Zumbalamambo Please try the latest development wheel.

**Comment by Zumbalamambo** [comment] 2021-03-14 21:51
@ssheorey may I know where can I find the development wheel?

**Comment by ssheorey** [comment] 2021-03-15 15:58
http://www.open3d.org/docs/latest/getting_started.html#development-version-pip

**Closed** 2021-03-16 22:54 UTC
Labels: sensors
