### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by TheBricktop** [intel-isl/Open3D#1487] opened 2020-02-03 10:25 UTC
Is there a quick intro tutorial how to get into Open3d on win10?

**Comment by xiaohulihutu** [comment] 2020-02-03 10:33
I m new to coding but i can use open3d 0.7.0.0 on win10. Just pip install open3d-python, done. I have tried hard to import the latest version but keep getting error shown below.

from .open3d import * # py2 py3 compatible
ImportError: DLL load failed: The specified module could not be found.

Trying hard to figure it out.

**Comment by SeanStephensenAIRM** [comment] 2020-02-05 23:14
Using open3d 0.9.0.0 with windows 10 currently. Set up a python 3.6 virtual environment in pycharm and use the package installer to install open3d (not open3d-python)

**Comment by xiaohulihutu** [comment] 2020-02-06 16:52
> Using open3d 0.9.0.0 with windows 10 currently. Set up a python 3.6 virtual environment in pycharm and use the package installer to install open3d (not open3d-python)

Good to know, thanks. I am using VSCode with Python 3.7. I have tried 2.7 as well but same error. Just dont know whats wrong with my VSCode.

**Comment by SeanStephensenAIRM** [comment] 2020-02-06 16:56
hmm, haven't tried python in VSCode, but it should be similar. I wasn't able to get anything installed on python 3.7 or 3.8, but downgrading to 3.6 in a venv instantly worked. If you can setup a similar venv in VSC, should be able to get things working. Not sure if VSC has a package installer, but command line install should work as well as long as you check that the terminal is accessing the right python. That being said, open3d website claims that python 2.7 should work as well.

**Comment by chaslie** [comment] 2020-02-17 08:54
> I m new to coding but i can use open3d 0.7.0.0 on win10. Just pip install open3d-python, done. I have tried hard to import the latest version but keep getting error shown below.
> from .open3d import * # py2 py3 compatible
> ImportError: DLL load failed: The specified module could not be found.
> Trying hard to figure it out.

I did a conda update and this solved the problem - good luck....

**Comment by germanros1987** [comment] 2020-02-19 21:54
@TheBricktop is your question addressed?

**Comment by TheBricktop** [comment] 2020-02-21 13:48
ye

**Comment by syncle** [comment] 2020-02-21 20:17
How about just trying ``pip install open3d``? It is more official way to install :)

BTW, the DLL error may be due to the virtual environment issue. @yxlao, I found we had received same question before #1452, #1421, #979. Some users had to [downgrade Open3D](https://github.com/intel-isl/Open3D/issues/979#issuecomment-568257119), [install windows redistributable](https://github.com/intel-isl/Open3D/issues/979#issuecomment-541023476), change [Python version](https://github.com/intel-isl/Open3D/issues/979#issuecomment-557655171), [remove "dot" when importing open3d](https://github.com/intel-isl/Open3D/issues/979#issuecomment-576644924). 
Could you have a look and give a comment on this?

**Comment by yxlao** [comment] 2020-02-28 08:58
Hi, I tested Open3D `0.9.0` pip and Conda installation under Windows 10 64-bit with python3.7 and they're all working for me. 

Here's the full terminal recording for `pip install`:
https://terminalizer.com/view/fcc321e93273

Here's the full terminal recording for `conda install`:
https://terminalizer.com/view/0c3811b03274

Please try with the exact same command (including creating a fresh environment and activating it), and see if the problem still exists.

**Comment by limgm** [comment] 2020-02-28 12:13
Hi @yxlao  I just tried the same command for `conda install ` but the problem still exists on my machine
Windows 10 64-bit with python3.7

**Comment by yxlao** [comment] 2020-02-28 12:15
@limgm can you post a full terminal log?

**Comment by limgm** [comment] 2020-02-28 12:15
(base) C:\Users\User>conda list env
# packages in environment at D:\ProgramFiles\Anaconda3:
#
# Name                    Version                   Build  Channel
conda-env                 2.6.0                h36134e3_1

(base) C:\Users\User>conda env list
# conda environments:
#
base                  *  D:\ProgramFiles\Anaconda3
dl                       D:\ProgramFiles\Anaconda3\envs\dl
kv2                      D:\ProgramFiles\Anaconda3\envs\kv2
rris                     D:\ProgramFiles\Anaconda3\envs\rris


(base) C:\Users\User>conda create -n py37-conda python=3.7
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: D:\ProgramFiles\Anaconda3\envs\py37-conda

  added / updated specs:
    - python=3.7


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2019.11.28         |           py37_0         157 KB
    pip-20.0.2                 |           py37_1         1.9 MB
    python-3.7.6               |       h60c2a47_2        18.3 MB
    setuptools-45.2.0          |           py37_0         674 KB
    vc-14.1                    |       h0510ff6_4           6 KB
    wheel-0.34.2               |           py37_0          67 KB
    wincertstore-0.2           |           py37_0          13 KB
    ------------------------------------------------------------
                                           Total:        21.2 MB

The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/win-64::ca-certificates-2020.1.1-0
  certifi            pkgs/main/win-64::certifi-2019.11.28-py37_0
  openssl            pkgs/main/win-64::openssl-1.1.1d-he774522_4
  pip                pkgs/main/win-64::pip-20.0.2-py37_1
  python             pkgs/main/win-64::python-3.7.6-h60c2a47_2
  setuptools         pkgs/main/win-64::setuptools-45.2.0-py37_0
  sqlite             pkgs/main/win-64::sqlite-3.31.1-he774522_0
  vc                 pkgs/main/win-64::vc-14.1-h0510ff6_4
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.16.27012-hf0eaf9b_1
  wheel              pkgs/main/win-64::wheel-0.34.2-py37_0
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py37_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
python-3.7.6         | 18.3 MB   | ############################################################################ | 100%
certifi-2019.11.28   | 157 KB    | ############################################################################ | 100%
wincertstore-0.2     | 13 KB     | ############################################################################ | 100%
wheel-0.34.2         | 67 KB     | ############################################################################ | 100%
setuptools-45.2.0    | 674 KB    | ############################################################################ | 100%
pip-20.0.2           | 1.9 MB    | ############################################################################ | 100%
vc-14.1              | 6 KB      | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate py37-conda
#
# To deactivate an active environment, use
#
#     $ conda deactivate


(base) C:\Users\User>conda activate py37-conda

(py37-conda) C:\Users\User>python --version
Python 3.7.6

(py37-conda) C:\Users\User>conda install -c open3d-admin open3d
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: D:\ProgramFiles\Anaconda3\envs\py37-conda

  added / updated specs:
    - open3d


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    backcall-0.1.0             |           py37_0          19 KB
    blas-1.0                   |              mkl           6 KB
    bleach-3.1.0               |           py37_0         222 KB
    entrypoints-0.3            |           py37_0          12 KB
    importlib_metadata-1.5.0   |           py37_0          48 KB
    intel-openmp-2020.0        |              166         1.9 MB
    ipykernel-5.1.4            |   py37h39e3cac_0         168 KB
    ipython-7.12.0             |   py37h5ca1d4c_0         1.1 MB
    ipython_genutils-0.2.0     |           py37_0          39 KB
    jedi-0.16.0                |           py37_0         783 KB
    jsonschema-3.2.0           |           py37_0         112 KB
    jupyter_client-5.3.4       |           py37_0         160 KB
    jupyter_core-4.6.1         |           py37_0          97 KB
    markupsafe-1.1.1           |   py37he774522_0          32 KB
    mistune-0.8.4              |   py37he774522_0          54 KB
    mkl-2020.0                 |              166       156.1 MB
    mkl-service-2.3.0          |   py37hb782905_0         200 KB
    mkl_fft-1.0.15             |   py37h14836fe_0         137 KB
    mkl_random-1.1.0           |   py37h675688f_0         270 KB
    msys2-conda-epoch-20160418 |                1           2 KB
    nbconvert-5.6.1            |           py37_0         512 KB
    notebook-6.0.3             |           py37_0         7.8 MB
    numpy-1.18.1               |   py37h93ca92e_0           5 KB
    numpy-base-1.18.1          |   py37hc3f5095_1         4.8 MB
    open3d-0.9.0.0             |           py37_0         2.1 MB  open3d-admin
    pandocfilters-1.4.2        |           py37_1          13 KB
    pickleshare-0.7.5          |           py37_0          13 KB
    prompt_toolkit-3.0.3       |             py_0         236 KB
    pyrsistent-0.15.7          |   py37he774522_0          95 KB
    pywin32-227                |   py37he774522_1         9.5 MB
    pywinpty-0.5.7             |           py37_0          54 KB
    pyzmq-18.1.1               |   py37ha925a31_0         443 KB
    send2trash-1.5.0           |           py37_0          16 KB
    six-1.14.0                 |           py37_0          27 KB
    terminado-0.8.3            |           py37_0          25 KB
    tornado-6.0.3              |   py37he774522_3         647 KB
    traitlets-4.3.3            |           py37_0         138 KB
    webencodings-0.5.1         |           py37_1          19 KB
    widgetsnbextension-3.5.1   |           py37_0         1.8 MB
    ------------------------------------------------------------
                                           Total:       189.7 MB

The following NEW packages will be INSTALLED:

  attrs              pkgs/main/noarch::attrs-19.3.0-py_0
  backcall           pkgs/main/win-64::backcall-0.1.0-py37_0
  blas               pkgs/main/win-64::blas-1.0-mkl
  bleach             pkgs/main/win-64::bleach-3.1.0-py37_0
  colorama           pkgs/main/noarch::colorama-0.4.3-py_0
  decorator          pkgs/main/noarch::decorator-4.4.1-py_0
  defusedxml         pkgs/main/noarch::defusedxml-0.6.0-py_0
  entrypoints        pkgs/main/win-64::entrypoints-0.3-py37_0
  icc_rt             pkgs/main/win-64::icc_rt-2019.0.0-h0cc432a_1
  importlib_metadata pkgs/main/win-64::importlib_metadata-1.5.0-py37_0
  intel-openmp       pkgs/main/win-64::intel-openmp-2020.0-166
  ipykernel          pkgs/main/win-64::ipykernel-5.1.4-py37h39e3cac_0
  ipython            pkgs/main/win-64::ipython-7.12.0-py37h5ca1d4c_0
  ipython_genutils   pkgs/main/win-64::ipython_genutils-0.2.0-py37_0
  ipywidgets         pkgs/main/noarch::ipywidgets-7.5.1-py_0
  jedi               pkgs/main/win-64::jedi-0.16.0-py37_0
  jinja2             pkgs/main/noarch::jinja2-2.11.1-py_0
  jsonschema         pkgs/main/win-64::jsonschema-3.2.0-py37_0
  jupyter_client     pkgs/main/win-64::jupyter_client-5.3.4-py37_0
  jupyter_core       pkgs/main/win-64::jupyter_core-4.6.1-py37_0
  libsodium          pkgs/main/win-64::libsodium-1.0.16-h9d3ae62_0
  m2w64-gcc-libgfor~ pkgs/msys2/win-64::m2w64-gcc-libgfortran-5.3.0-6
  m2w64-gcc-libs     pkgs/msys2/win-64::m2w64-gcc-libs-5.3.0-7
  m2w64-gcc-libs-co~ pkgs/msys2/win-64::m2w64-gcc-libs-core-5.3.0-7
  m2w64-gmp          pkgs/msys2/win-64::m2w64-gmp-6.1.0-2
  m2w64-libwinpthre~ pkgs/msys2/win-64::m2w64-libwinpthread-git-5.0.0.4634.697f757-2
  markupsafe         pkgs/main/win-64::markupsafe-1.1.1-py37he774522_0
  mistune            pkgs/main/win-64::mistune-0.8.4-py37he774522_0
  mkl                pkgs/main/win-64::mkl-2020.0-166
  mkl-service        pkgs/main/win-64::mkl-service-2.3.0-py37hb782905_0
  mkl_fft            pkgs/main/win-64::mkl_fft-1.0.15-py37h14836fe_0
  mkl_random         pkgs/main/win-64::mkl_random-1.1.0-py37h675688f_0
  msys2-conda-epoch  pkgs/msys2/win-64::msys2-conda-epoch-20160418-1
  nbconvert          pkgs/main/win-64::nbconvert-5.6.1-py37_0
  nbformat           pkgs/main/noarch::nbformat-5.0.4-py_0
  notebook           pkgs/main/win-64::notebook-6.0.3-py37_0
  numpy              pkgs/main/win-64::numpy-1.18.1-py37h93ca92e_0
  numpy-base         pkgs/main/win-64::numpy-base-1.18.1-py37hc3f5095_1
  open3d             open3d-admin/win-64::open3d-0.9.0.0-py37_0
  pandoc             pkgs/main/win-64::pandoc-2.2.3.2-0
  pandocfilters      pkgs/main/win-64::pandocfilters-1.4.2-py37_1
  parso              pkgs/main/noarch::parso-0.6.1-py_0
  pickleshare        pkgs/main/win-64::pickleshare-0.7.5-py37_0
  prometheus_client  pkgs/main/noarch::prometheus_client-0.7.1-py_0
  prompt_toolkit     pkgs/main/noarch::prompt_toolkit-3.0.3-py_0
  pygments           pkgs/main/noarch::pygments-2.5.2-py_0
  pyrsistent         pkgs/main/win-64::pyrsistent-0.15.7-py37he774522_0
  python-dateutil    pkgs/main/noarch::python-dateutil-2.8.1-py_0
  pywin32            pkgs/main/win-64::pywin32-227-py37he774522_1
  pywinpty           pkgs/main/win-64::pywinpty-0.5.7-py37_0
  pyzmq              pkgs/main/win-64::pyzmq-18.1.1-py37ha925a31_0
  send2trash         pkgs/main/win-64::send2trash-1.5.0-py37_0
  six                pkgs/main/win-64::six-1.14.0-py37_0
  terminado          pkgs/main/win-64::terminado-0.8.3-py37_0
  testpath           pkgs/main/noarch::testpath-0.4.4-py_0
  tornado            pkgs/main/win-64::tornado-6.0.3-py37he774522_3
  traitlets          pkgs/main/win-64::traitlets-4.3.3-py37_0
  wcwidth            pkgs/main/noarch::wcwidth-0.1.8-py_0
  webencodings       pkgs/main/win-64::webencodings-0.5.1-py37_1
  widgetsnbextension pkgs/main/win-64::widgetsnbextension-3.5.1-py37_0
  winpty             pkgs/main/win-64::winpty-0.4.3-4
  zeromq             pkgs/main/win-64::zeromq-4.3.1-h33f27b4_3
  zipp               pkgs/main/noarch::zipp-2.2.0-py_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
ipython_genutils-0.2 | 39 KB     | ############################################################################ | 100%
nbconvert-5.6.1      | 512 KB    | ############################################################################ | 100%
jupyter_core-4.6.1   | 97 KB     | ############################################################################ | 100%
pickleshare-0.7.5    | 13 KB     | ############################################################################ | 100%
tornado-6.0.3        | 647 KB    | ############################################################################ | 100%
open3d-0.9.0.0       | 2.1 MB    | ############################################################################ | 100%
numpy-1.18.1         | 5 KB      | ############################################################################ | 100%
numpy-base-1.18.1    | 4.8 MB    | ############################################################################ | 100%
backcall-0.1.0       | 19 KB     | ############################################################################ | 100%
send2trash-1.5.0     | 16 KB     | ############################################################################ | 100%
traitlets-4.3.3      | 138 KB    | ############################################################################ | 100%
ipykernel-5.1.4      | 168 KB    | ############################################################################ | 100%
jupyter_client-5.3.4 | 160 KB    | ############################################################################ | 100%
jedi-0.16.0          | 783 KB    | ############################################################################ | 100%
blas-1.0             | 6 KB      | ############################################################################ | 100%
entrypoints-0.3      | 12 KB     | ############################################################################ | 100%
mistune-0.8.4        | 54 KB     | ############################################################################ | 100%
markupsafe-1.1.1     | 32 KB     | ############################################################################ | 100%
importlib_metadata-1 | 48 KB     | ############################################################################ | 100%
pyzmq-18.1.1         | 443 KB    | ############################################################################ | 100%
jsonschema-3.2.0     | 112 KB    | ############################################################################ | 100%
notebook-6.0.3       | 7.8 MB    | ############################################################################ | 100%
six-1.14.0           | 27 KB     | ############################################################################ | 100%
pywin32-227          | 9.5 MB    | ############################################################################ | 100%
pywinpty-0.5.7       | 54 KB     | ############################################################################ | 100%
msys2-conda-epoch-20 | 2 KB      | ############################################################################ | 100%
mkl-2020.0           | 156.1 MB  | ############################################################################ | 100%
mkl-service-2.3.0    | 200 KB    | ############################################################################ | 100%
pyrsistent-0.15.7    | 95 KB     | ############################################################################ | 100%
intel-openmp-2020.0  | 1.9 MB    | ############################################################################ | 100%
webencodings-0.5.1   | 19 KB     | ############################################################################ | 100%
terminado-0.8.3      | 25 KB     | ############################################################################ | 100%
widgetsnbextension-3 | 1.8 MB    | ############################################################################ | 100%
mkl_fft-1.0.15       | 137 KB    | ############################################################################ | 100%
prompt_toolkit-3.0.3 | 236 KB    | ############################################################################ | 100%
mkl_random-1.1.0     | 270 KB    | ############################################################################ | 100%
pandocfilters-1.4.2  | 13 KB     | ############################################################################ | 100%
ipython-7.12.0       | 1.1 MB    | ############################################################################ | 100%
bleach-3.1.0         | 222 KB    | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: | DEBUG menuinst_win32:__init__(196): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'D:\ProgramFiles\Anaconda3\envs\py37-conda', env_name: 'py37-conda', mode: 'user', used_mode: 'user'
DEBUG menuinst_win32:create(320): Shortcut cmd is D:\ProgramFiles\Anaconda3\python.exe, args are ['D:\\ProgramFiles\\Anaconda3\\cwp.py', 'D:\\ProgramFiles\\Anaconda3\\envs\\py37-conda', 'D:\\ProgramFiles\\Anaconda3\\envs\\py37-conda\\python.exe', 'D:\\ProgramFiles\\Anaconda3\\envs\\py37-conda\\Scripts\\jupyter-notebook-script.py', '"%USERPROFILE%/"']
done

(py37-conda) C:\Users\User>python
Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import open3d as o3d
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\ProgramFiles\Anaconda3\envs\py37-conda\lib\site-packages\open3d\__init__.py", line 35, in <module>
    from .open3d import * # py2 py3 compatible
ImportError: DLL load failed: The specified module could not be found.
>>> ^Z

**Comment by yxlao** [comment] 2020-02-28 12:25
Can you `dir` the installation directory: `D:\ProgramFiles\Anaconda3\envs\py37-conda\lib\site-packages\open3d`

**Comment by limgm** [comment] 2020-02-28 12:27
```

 Directory of D:\ProgramFiles\Anaconda3\envs\py37-conda\Lib\site-packages\open3d

28/02/2020  08:11 PM    <DIR>          .
28/02/2020  08:11 PM    <DIR>          ..
20/12/2019  01:43 PM             3,755 j_visualizer.py
20/12/2019  01:43 PM         6,109,696 open3d.cp37-win_amd64.pyd
28/02/2020  08:15 PM             2,063 __init__.py
28/02/2020  08:11 PM    <DIR>          __pycache__
               3 File(s)      6,115,514 bytes
               3 Dir(s)  700,752,904,192 bytes free
```

**Comment by yxlao** [comment] 2020-02-28 12:33
Thanks, looks like the open3d library is there `open3d.cp37-win_amd64.pyd`. This is probably due to some system runtime library versions. Can you try with attempt 1 and then attempt 2 as follows?

Attempt 1:
From https://support.microsoft.com/en-my/help/2977003/the-latest-supported-visual-c-downloads, download the `vc_redist.x64.exe` and install. Or, use this direct link: https://aka.ms/vs/16/release/vc_redist.x64.exe.

Attempt 2;
From https://visualstudio.microsoft.com/downloads/, download the VS2019, and select the C++ component during your installation.

**Comment by limgm** [comment] 2020-02-28 12:39
I tried attempt 1 and the error is not present
```
(py37-conda) C:\Users\User>python
Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import open3d as o3d
>>> o3d
<module 'open3d' from 'D:\\ProgramFiles\\Anaconda3\\envs\\py37-conda\\lib\\site-packages\\open3d\\__init__.py'>
>>> o3d.__version__
'0.9.0.0'
```

But when i try a basic example there is some error, is it related?
```
(py37-conda) C:\Users\User\Downloads\Open3D-master\examples\Python\Basic>python bounding_volume.py
Traceback (most recent call last):
  File "bounding_volume.py", line 32, in <module>
    for name, geom in mesh_generator():
  File "bounding_volume.py", line 21, in mesh_generator
    mesh = o3d.geometry.TriangleMesh.create_box()
AttributeError: module 'open3d' has no attribute 'geometry'
```

Thanks for your help

**Comment by yxlao** [comment] 2020-02-28 12:48
Perfect, if attempt 1 is working then no need to try attempt 2.

The ` module 'open3d' has no attribute 'geometry'` is another issue. Can you simply try the following (attaching my terminal output):

```batch
(py37) python -c "import open3d as o3d; print(o3d.geometry)"
<module 'open3d.open3d.geometry'>
```

**Comment by limgm** [comment] 2020-02-28 12:51
```
(py37-conda) C:\Users\User>python -c "import open3d as o3d; print(o3d.geometry)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'open3d' has no attribute 'geometry'
```

**Comment by yxlao** [comment] 2020-02-28 12:54
What about this?

```batch
(py37) λ python -c "import open3d as o3d; print(dir(o3d))"
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'camera', 'color_map', 'geometry', 'integration', 'io', 'odometry', 'open3d', 'registration', 'utility', 'visualization']
```

**Comment by limgm** [comment] 2020-02-28 12:55
```
(py37-conda) C:\Users\User>python -c "import open3d as o3d; print(dir(o3d))"
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__']
```

**Comment by yxlao** [comment] 2020-02-28 12:56
That's very strange. Can you try re-creating a new conda environment, and install open3d (after you have already installed the vc2019 runtime)?

**Comment by yxlao** [comment] 2020-02-28 12:58
If it still doesn't work, could you try attempt 2?

**Comment by limgm** [comment] 2020-02-28 13:15
Hi @yxlao thank you very much attempt 2 works!

I also removed the old env, recreate a new conda env, install open3d and now it is working fine!

**Comment by syncle** [comment] 2020-02-28 16:03
Thanks, guys, the reported issue is not reproducible with up-to-date python env and open3d package. Closing issue.

**Closed by syncle** 2020-02-28 16:03 UTC
Labels: feature request

**Comment by davidemariafabris** [comment] 2020-04-17 19:27
I get the same error, I cannot solve it.

from .open3d import * # py2 py3 compatible
ImportError: DLL load failed:

**Comment by BingXiong1995** [comment] 2020-05-07 23:52
@davidemariafabris  try 
from open3d import 
juest delete the dot

**Comment by darkworks** [comment] 2021-12-15 14:31
> @davidemariafabris try from open3d import juest delete the dot

it was helpful in removing error : `from .open3d import * # py2 py3 compatible`

now getting
`AttributeError: module 'open3d' has no attribute 'geometry'`

any idea how to fix this
