### ISSUE TITLE
icp_registration

### ISSUE THREAD

**Issue by coolinfan20** [intel-isl/Open3D#820] opened 2019-02-07 16:07 UTC
Hi, I am fairly new to point clouds and had a questions about using the icp_registration and global_registration codes to align customized point clouds. When I import my own pcd files, I get the the following error message: 

Error: TransformationEstimationPointToPlane requires pre-computed normal vectors.
RegistrationResult with fitness = 0.000000, inlier_rmse = 0.000000, and correspondence_set size of 0
Access transformation to get result.
Transformation is:
[[ 0.862  0.011 -0.507  0.5  ]
 [-0.139  0.967 -0.215  0.7  ]
 [ 0.487  0.255  0.835 -1.4  ]
 [ 0.     0.     0.     1.   ]]

Could you explain how I calculate the pre-computed normal vectors? I tried importing the global_registration code to get the normals since the documentation says that the global registration is used to initialize the local methods?

Thanks!

**Comment by syncle** [comment] 2019-02-07 20:16
Hi @coolinfan20. Please [read this tutorial](http://open3d.org/docs/tutorial/Basic/icp_registration.html#point-to-plane-icp). In short, Point-to-Plane ICP requires vertex normal, so you need to compute before using it. 

This is duplicate of #468.

**Comment by coolinfan20** [comment] 2019-02-11 16:06
I used the estimate_normals to get a vector of normals for my source and target point clouds using the following code:

`estimate_normals(downsource, search_param = KDTreeSearchParamHybrid(
            radius = 0.1, max_nn = 30))`
 `estimate_normals(downtarget, search_param = KDTreeSearchParamHybrid(
            radius = 0.1, max_nn = 30))`

`reg_p2l = registration_icp(source, target, threshold, trans_init,
            TransformationEstimationPointToPlane(np.asarray(downsource.normals)[:,:]))`

but end up with this error message: TransformationEstimationPointToPlane(np.asarray(downsource.normals)[:,:]))
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. open3d.open3d.registration.TransformationEstimationPointToPlane()
    2. open3d.open3d.registration.TransformationEstimationPointToPlane(arg0: open3d.open3d.registration.TransformationEstimationPointToPlane)

What is the correct syntax for TransformationEstimationPointToPlane? Also, do I need to pass it the normal vectors for both the source and the target?

**Comment by syncle** [comment] 2019-02-11 18:08
``estimate_normals`` is inplace function - this means that you will have vertex normal inside ``downsource`` and ``downtarget``. You don't have to explicitly pass normals. Just try
```
estimate_normals(downsource, search_param = KDTreeSearchParamHybrid( radius = 0.1, max_nn = 30))
estimate_normals(downtarget, search_param = KDTreeSearchParamHybrid( radius = 0.1, max_nn = 30))
reg_p2l = registration_icp(downsource, downtarget, threshold, trans_init, TransformationEstimationPointToPlane())
```

**Comment by coolinfan20** [comment] 2019-02-11 22:53
![initial](https://user-images.githubusercontent.com/47425198/52598918-6c237f00-2e14-11e9-92bd-420d67571117.png)
![transformation](https://user-images.githubusercontent.com/47425198/52598920-6c237f00-2e14-11e9-858d-f0b6836a8553.png)

Now that I've calculated the normals vectors, I am able to execute the registration_icp function, but I still am unable to get my two point clouds to align properly. I have tried changing the voxel_size and adding the ICP convergence criteria to try to get it to iterate more times, but the point clouds either don't change or do not fully align.

Thanks!

**Comment by syncle** [comment] 2019-02-12 22:19
Point cloud registration method is not guaranteed to align any point clouds - see the previous discussions in #359.

**Comment by coolinfan20** [comment] 2019-02-19 21:42
Regarding your previous comment, I thought the purpose of point cloud registration was to align two point clouds?

However, it seems that by voxelizing the point clouds, I was able to get it to register some of the point clouds. I was playing around with the voxel size and found that even with the same set of point clouds and voxel sizes, the fitness, inlier_rmse, and correspondence sizes will vary. Do you know why this is?

**Comment by coolinfan20** [comment] 2019-02-19 22:28
I also had a few more questions regarding the RMSE error: I added the ICPConvergenceCriteria the registration_icp of your Global Registration code because I wanted the transformation that would minimize the RMSE, so I changed the parameter to relative_rmse instead of max_iteration (from the ICP registration demo code); however, the inlier_rmse continues to fluctuate and often times is nowhere close to the relative_rmse parameter I set. 

So I am wondering what the difference is between inlier_rmse and relative_rmse? What would make the inlier_rmse more consistent?

Also, I am assuming the correspondence_set size is how many points between the points clouds are aligned? If this is correct, I am also wondering why this value will have significant fluctuations (sometimes more than 500 for a downsized point cloud containing only ~4000 points) even though the transformation is relatively the same?

Thanks!

**Comment by edwincasallas22** [comment] 2019-10-17 20:31
> Utilicé el estimativo_normals para obtener un vector de normales para mis nubes de puntos de origen y destino usando el siguiente código:
> 
> `estimate_normals(downsource, search_param = KDTreeSearchParamHybrid( radius = 0.1, max_nn = 30))`
> `estimate_normals(downtarget, search_param = KDTreeSearchParamHybrid( radius = 0.1, max_nn = 30))`
> 
> `reg_p2l = registration_icp(source, target, threshold, trans_init, TransformationEstimationPointToPlane(np.asarray(downsource.normals)[:,:]))`
> 
> pero termina con este mensaje de error: TransformationEstimationPointToPlane (np.asarray (downsource.normals) [:,:])) 
> TypeError: **init** (): argumentos de constructor incompatibles. Se admiten los siguientes tipos de argumentos: 
> 1. open3d.open3d.registration.TransformationEstimationPointToPlane () 
> 2. open3d.open3d.registration.TransformationEstimationPointToPlane (arg0: open3d.open3d.registration.TransformationEstimationPointToPlane)
> 
> ¿Cuál es la sintaxis correcta para TransformationEstimationPointToPlane? Además, ¿debo pasarle los vectores normales tanto para el origen como para el destino?



> I used the estimate_normals to get a vector of normals for my source and target point clouds using the following code:
> 
> `estimate_normals(downsource, search_param = KDTreeSearchParamHybrid( radius = 0.1, max_nn = 30))`
> `estimate_normals(downtarget, search_param = KDTreeSearchParamHybrid( radius = 0.1, max_nn = 30))`
> 
> `reg_p2l = registration_icp(source, target, threshold, trans_init, TransformationEstimationPointToPlane(np.asarray(downsource.normals)[:,:]))`
> 
> but end up with this error message: TransformationEstimationPointToPlane(np.asarray(downsource.normals)[:,:]))
> TypeError: **init**(): incompatible constructor arguments. The following argument types are supported:
> 1. open3d.open3d.registration.TransformationEstimationPointToPlane()
> 2. open3d.open3d.registration.TransformationEstimationPointToPlane(arg0: open3d.open3d.registration.TransformationEstimationPointToPlane)
> 
> What is the correct syntax for TransformationEstimationPointToPlane? Also, do I need to pass it the normal vectors for both the source and the target?

Did you fix this problem? 
How did you define estimate_normals in the algorithm? 
I put this part of the code in the main and I get the following error:

[Open3D WARNING] TransformationEstimationPointToPlane requires pre-computed normal vectors.
registration::RegistrationResult with fitness = 0.000000, inlier_rmse = 0.000000, and correspondence_set size of 0
Access transformation to get result.
Traceback (most recent call last):
  File "global_registration.py", line 104, in <module>
    estimate_normals(source, search_param = KDTreeSearchParamHybrid( radius = 0.1, max_nn = 30))
NameError: name 'estimate_normals' is not defined

Could you help me ?

**Comment by germanros1987** [comment] 2020-07-27 23:33
Issue closed due to lack of activity. Feel free to open a new issue if you still consider this is a critical matter.

**Closed by germanros1987** 2020-07-27 23:33 UTC
Labels: duplicate
