### ISSUE TITLE
Is there a way to find closest points on mesh surface to points in a cloud

### ISSUE THREAD

**Issue by grosskc** [intel-isl/Open3D#1195] opened 2019-09-20 13:15 UTC
Dear Open3D users.

I am looking to use Open3D to precisely fit a measured point cloud to an accurate CAD model. I am successful in achieving this by generating a point cloud representation of the CAD model via sampling. To achieve the desired accuracy, I must highly sample the CAD model.

It seems a more efficient approach could be achieved by iteratively fitting my measured point cloud to the nearest points on the mesh. Is this currently possible in Open3D?

The great Python package trimesh has this capability -- see [Trimesh Proximity functions](https://github.com/mikedh/trimesh/blob/master/trimesh/proximity.py) -- nicely integrated into their [ICP implementation](https://github.com/mikedh/trimesh/blob/master/trimesh/registration.py) for fitting points to a mesh, but it is too slow for my application.

Thanks in advance for any information!

**Comment by syncle** [comment] 2020-02-27 13:19
Thanks for the suggestion. Unfortunately, given basic Open3D's functions, the suggested way (sampling from mesh) is a viable solution for now. It would be great if you can contribute!

**Comment by vijaysamula** [comment] 2020-05-27 12:45
Hi grosskc,
           I am having the same problem when comparing the CAD with point cloud model. Can I know the approach?

**Comment by germanros1987** [comment] 2020-08-07 04:18
@griegler do you think this is something you could help with?

**Comment by griegler** [comment] 2020-08-07 06:36
Duplicate of #2062

**Closed by griegler** 2020-08-07 06:36 UTC
Labels: question
