### ISSUE TITLE
ConvertFromPinholeCameraParameters failed in the example tutorial

### ISSUE THREAD

**Issue by whatseven** [intel-isl/Open3D#762] opened 2019-01-03 04:33 UTC
**Describe the bug**
Can not run `customized_visualization.py` in examples when I pull the official repo. Having warnings `[ViewControl] ConvertFromPinholeCameraParameters() failed because window height and width do not match.`

**To Reproduce**
1. pull the official repo
2. Go to `examples\Python\Advanced`
3. run git bash in this folder
4. Run `python customized_visualization.py`

**Expected behavior**
When reach 
```
print("6. Customized visualization playing a camera trajectory")
custom_draw_geometry_with_camera_trajectory(pcd)
```
It must do as the tutorial shows to capture images along a trajectory, but the view change is failed

**Desktop (please complete the following information):**
 - OS: win10
 - Python: 3.6.5

**Comment by zy871125746** [comment] 2019-01-03 06:43
I have got the same output when I tried it.

**Comment by syncle** [comment] 2019-01-03 08:37
Umm I just tried with win10, but couldn't reproduce the issue. Can you double check that the pip package was built from source?

**Comment by whatseven** [comment] 2019-01-03 12:00
No, I got the same results. Maybe I miss some steps? Here are my steps to get the library:

1. clone the repo
2. use cmake to generate sln files. Cmake do find the path of the python executable
3. open the sln file and build the `all_build` project, then right click the `install-pip-package` and build it

```
4>------ 已启动生成: 项目: install-pip-package, 配置: Release x64 ------
4>Building Custom Rule C:/Users/whatseven/Desktop/Open3D/src/Python/CMakeLists.txt
4>CMake does not need to re-run because C:/Users/whatseven/Desktop/Open3D/build/src/Python/CMakeFiles/generate.stamp is up-to-date.
4>Processing c:\users\whatseven\desktop\open3d\build\lib\python_package\pip_package\open3d-0.4.0.0-cp36-cp36m-win_amd64.whl
4>Requirement already satisfied, skipping upgrade: widgetsnbextension in c:\sdk\python3_6_5_64\lib\site-packages (from open3d==0.4.0.0) (3.4.2)
4>Requirement already satisfied, skipping upgrade: numpy in c:\sdk\python3_6_5_64\lib\site-packages (from open3d==0.4.0.0) (1.15.0)
4>Requirement already satisfied, skipping upgrade: ipywidgets in c:\sdk\python3_6_5_64\lib\site-packages (from open3d==0.4.0.0) (7.4.2)
4>Requirement already satisfied, skipping upgrade: notebook in c:\sdk\python3_6_5_64\lib\site-packages (from open3d==0.4.0.0) (5.7.4)
4>Requirement already satisfied, skipping upgrade: traitlets>=4.3.1 in c:\sdk\python3_6_5_64\lib\site-packages (from ipywidgets->open3d==0.4.0.0) (4.3.2)
4>Requirement already satisfied, skipping upgrade: ipykernel>=4.5.1 in c:\sdk\python3_6_5_64\lib\site-packages (from ipywidgets->open3d==0.4.0.0) (4.8.2)
4>Requirement already satisfied, skipping upgrade: nbformat>=4.2.0 in c:\sdk\python3_6_5_64\lib\site-packages (from ipywidgets->open3d==0.4.0.0) (4.4.0)
4>Requirement already satisfied, skipping upgrade: ipython>=4.0.0; python_version >= "3.3" in c:\sdk\python3_6_5_64\lib\site-packages (from ipywidgets->open3d==0.4.0.0) (7.2.0)
4>Requirement already satisfied, skipping upgrade: Send2Trash in c:\sdk\python3_6_5_64\lib\site-packages (from notebook->open3d==0.4.0.0) (1.5.0)
4>Requirement already satisfied, skipping upgrade: jupyter-core>=4.4.0 in c:\sdk\python3_6_5_64\lib\site-packages (from notebook->open3d==0.4.0.0) (4.4.0)
4>Requirement already satisfied, skipping upgrade: nbconvert in c:\sdk\python3_6_5_64\lib\site-packages (from notebook->open3d==0.4.0.0) (5.3.1)
4>Requirement already satisfied, skipping upgrade: pyzmq>=17 in c:\sdk\python3_6_5_64\lib\site-packages (from notebook->open3d==0.4.0.0) (17.1.0)
4>Requirement already satisfied, skipping upgrade: ipython-genutils in c:\sdk\python3_6_5_64\lib\site-packages (from notebook->open3d==0.4.0.0) (0.2.0)
4>Requirement already satisfied, skipping upgrade: prometheus-client in c:\sdk\python3_6_5_64\lib\site-packages (from notebook->open3d==0.4.0.0) (0.3.1)
4>Requirement already satisfied, skipping upgrade: terminado>=0.8.1 in c:\sdk\python3_6_5_64\lib\site-packages (from notebook->open3d==0.4.0.0) (0.8.1)
4>Requirement already satisfied, skipping upgrade: jinja2 in c:\sdk\python3_6_5_64\lib\site-packages (from notebook->open3d==0.4.0.0) (2.10)
4>Requirement already satisfied, skipping upgrade: tornado>=4 in c:\sdk\python3_6_5_64\lib\site-packages (from notebook->open3d==0.4.0.0) (4.5.3)
4>Requirement already satisfied, skipping upgrade: jupyter-client>=5.2.0 in c:\sdk\python3_6_5_64\lib\site-packages (from notebook->open3d==0.4.0.0) (5.2.3)
4>Requirement already satisfied, skipping upgrade: decorator in c:\sdk\python3_6_5_64\lib\site-packages (from traitlets>=4.3.1->ipywidgets->open3d==0.4.0.0) (4.3.0)
4>Requirement already satisfied, skipping upgrade: six in c:\sdk\python3_6_5_64\lib\site-packages (from traitlets>=4.3.1->ipywidgets->open3d==0.4.0.0) (1.11.0)
4>Requirement already satisfied, skipping upgrade: jsonschema!=2.5.0,>=2.4 in c:\sdk\python3_6_5_64\lib\site-packages (from nbformat>=4.2.0->ipywidgets->open3d==0.4.0.0) (2.6.0)
4>Requirement already satisfied, skipping upgrade: setuptools>=18.5 in c:\sdk\python3_6_5_64\lib\site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets->open3d==0.4.0.0) (39.0.1)
4>Requirement already satisfied, skipping upgrade: pygments in c:\sdk\python3_6_5_64\lib\site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets->open3d==0.4.0.0) (2.2.0)
4>Requirement already satisfied, skipping upgrade: colorama; sys_platform == "win32" in c:\sdk\python3_6_5_64\lib\site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets->open3d==0.4.0.0) (0.3.9)
4>Requirement already satisfied, skipping upgrade: pickleshare in c:\sdk\python3_6_5_64\lib\site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets->open3d==0.4.0.0) (0.7.4)
4>Requirement already satisfied, skipping upgrade: prompt-toolkit<2.1.0,>=2.0.0 in c:\sdk\python3_6_5_64\lib\site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets->open3d==0.4.0.0) (2.0.7)
4>Requirement already satisfied, skipping upgrade: backcall in c:\sdk\python3_6_5_64\lib\site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets->open3d==0.4.0.0) (0.1.0)
4>Requirement already satisfied, skipping upgrade: jedi>=0.10 in c:\sdk\python3_6_5_64\lib\site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets->open3d==0.4.0.0) (0.12.1)
4>Requirement already satisfied, skipping upgrade: entrypoints>=0.2.2 in c:\sdk\python3_6_5_64\lib\site-packages (from nbconvert->notebook->open3d==0.4.0.0) (0.2.3)
4>Requirement already satisfied, skipping upgrade: testpath in c:\sdk\python3_6_5_64\lib\site-packages (from nbconvert->notebook->open3d==0.4.0.0) (0.3.1)
4>Requirement already satisfied, skipping upgrade: mistune>=0.7.4 in c:\sdk\python3_6_5_64\lib\site-packages (from nbconvert->notebook->open3d==0.4.0.0) (0.8.3)
4>Requirement already satisfied, skipping upgrade: bleach in c:\sdk\python3_6_5_64\lib\site-packages (from nbconvert->notebook->open3d==0.4.0.0) (2.1.3)
4>Requirement already satisfied, skipping upgrade: pandocfilters>=1.4.1 in c:\sdk\python3_6_5_64\lib\site-packages (from nbconvert->notebook->open3d==0.4.0.0) (1.4.2)
4>Requirement already satisfied, skipping upgrade: pywinpty>=0.5; os_name == "nt" in c:\sdk\python3_6_5_64\lib\site-packages (from terminado>=0.8.1->notebook->open3d==0.4.0.0) (0.5.4)
4>Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in c:\sdk\python3_6_5_64\lib\site-packages (from jinja2->notebook->open3d==0.4.0.0) (1.0)
4>Requirement already satisfied, skipping upgrade: python-dateutil>=2.1 in c:\sdk\python3_6_5_64\lib\site-packages (from jupyter-client>=5.2.0->notebook->open3d==0.4.0.0) (2.7.3)
4>Requirement already satisfied, skipping upgrade: wcwidth in c:\sdk\python3_6_5_64\lib\site-packages (from prompt-toolkit<2.1.0,>=2.0.0->ipython>=4.0.0; python_version >= "3.3"->ipywidgets->open3d==0.4.0.0) (0.1.7)
4>Requirement already satisfied, skipping upgrade: parso>=0.3.0 in c:\sdk\python3_6_5_64\lib\site-packages (from jedi>=0.10->ipython>=4.0.0; python_version >= "3.3"->ipywidgets->open3d==0.4.0.0) (0.3.1)
4>Requirement already satisfied, skipping upgrade: html5lib!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8,>=0.99999999pre in c:\sdk\python3_6_5_64\lib\site-packages (from bleach->nbconvert->notebook->open3d==0.4.0.0) (1.0.1)
4>Requirement already satisfied, skipping upgrade: webencodings in c:\sdk\python3_6_5_64\lib\site-packages (from html5lib!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8,>=0.99999999pre->bleach->nbconvert->notebook->open3d==0.4.0.0) (0.5.1)
4>Installing collected packages: open3d
4>  Found existing installation: open3d 0.4.0.0
4>    Uninstalling open3d-0.4.0.0:
4>      Successfully uninstalled open3d-0.4.0.0
4>Successfully installed open3d-0.4.0.0
```

4. get into the example/advanced folder and run `python .\customized_visualization.py`

After that, I still failed to get view change in the 6th test case.

How can I check the version of my open3d, in the `__init__.py`, the version number is `0.4.0.0`

**Comment by syncle** [comment] 2019-01-03 17:53
Umm I am still trying to figure out what makes the issue.

**Try 1.**  Install Open3D Python using command line.
```
pip uninstall open3d-python
cmake --build . --config Release --target install-pip-package
```

**Try 2.**  ``ConvertFromPinholeCameraParameters() failed because window height and width do not match.`` message appears if the generated window size cannot reproduce the specified camera model. Can you check that the open3d window screen was created without cropping?

**Comment by whatseven** [comment] 2019-01-04 04:55
emmmm I reinstall the open3d and it does the same results. But after I turn my windows size small, it does work without warning. I want to do more testing on it, but I failed to generate my desired trajectory. 

Here is my code, but I can't get a right list of the `o_trajectory.parameters` after I append some items. The size is always 0. Did I miss some points about the trajectory?

```
        o_trajectory=PinholeCameraTrajectory()
        intrinsic = PinholeCameraIntrinsic(1920, 1080, 1344, 1344, 960, 540)
        with open(os.path.join(current_dir,"arg/camera_input")) as f:
            strs=f.readline()
            while strs:
                tokens=strs.split(",")
                # Below are just some matrixes, their types are 4*4 ndarray
                xaxis, yaxis, zaxis = [1, 0, 0], [0, 1, 0], [0, 0, 1]
                Rx = rotation_matrix(float(tokens[4]), xaxis)
                Ry = rotation_matrix(0, yaxis)
                Rz = rotation_matrix(float(tokens[6]), zaxis)
                R = concatenate_matrices(Rx, Ry, Rz)
                T = translation_matrix([float(tokens[1]),float(tokens[2]),float(tokens[3])])
                M = concatenate_matrices(T, R)
                extrinsic=M
                # Above are just some matrixes, their types are 4*4 ndarray
                camera_param=PinholeCameraParameters()
                camera_param.intrinsic=intrinsic
                camera_param.extrinsic=extrinsic
                o_trajectory.parameters.append(camera_param)

                strs = f.readline()

        write_pinhole_camera_trajectory(os.path.join(current_dir,"arg/trajectory.json"),o_trajectory)
```

**Comment by whatseven** [comment] 2019-01-04 16:20
I found that the window size will be `1920*1055` if I left the default setting `1920*1080`. And then the check will be failed.

**Comment by syncle** [comment] 2019-01-10 09:37
My quick answer: I think the code should produce the trajectory if ``f`` reads something. Regarding window size, I believe the windows shouldn't be larger than the screen size.

**Comment by zy871125746** [comment] 2019-01-16 06:04
I am using open3d 0.4.0.0 with python3.6 on ubuntu. And I have met the same Warnings. Is there any way that I can get the window size by python ?

**Comment by LittleLampChen** [comment] 2019-04-23 09:50
@zy871125746 I have meet the same problem with you and don't know how to fixed this

**Comment by yanghtr** [comment] 2019-09-22 20:25
I also met this problem when I use two screens with different resolutions (screen 1: 1920x1080, screen 2:1080x987).
I found that the open3d window will always automatically appear on screen 1.  When I ran the python script (window width and height are default) in screen 2 (the terminal where the script was run was in the screen 2), then there will be the "ConvertFromPinholeCameraParameters() failed because window height and width do not match" error. If I ran the python script in screen 1, then there will be no error.

I didn't know whether it had something to do with it.

When I fixed the window size with a smaller resolution (640x480) and print out the `vis.get_view_control().convert_to_pinhole_camera_parameters().intrinsic` and `trajectory.parameters[0].intrinsic`. I found that both the intrinsics (width and height ) are the same. However, if I ran the python script, no matter on which screen the script was run, they both will produce the "ConvertFromPinholeCameraParameters() failed because window height and width do not match" error.

I don't know what leads to the "ConvertFromPinholeCameraParameters() failed because window height and width do not match"  error?

**Comment by zhupan007** [comment] 2019-11-06 09:07
I also have this problem when I run customized_visualization.py , so what is the solution?

```
6. Customized visualization playing a camera trajectory
[Open3D WARNING] [ViewControl] ConvertFromPinholeCameraParameters() failed because window height and width do not match.
Capture image 00000
[Open3D WARNING] [ViewControl] ConvertFromPinholeCameraParameters() failed because window height and width do not match.
Capture image 00001
[Open3D WARNING] [ViewControl] ConvertFromPinholeCameraParameters() failed because window height and width do not match.
```

**Comment by Forest75** [comment] 2020-02-15 09:05
@whatseven Hi. Have you solved this problem? I try to append items to trajectory.parameters too, but it doesn't work.

**Comment by germanros1987** [comment] 2020-03-18 23:23
@syncle do we have any updates on this?

**Comment by mhudnell** [comment] 2020-04-29 22:30
@Forest75 I had the same problem appending to trajectory.parameters, I had to create a separate list and assign it's value.

```
trajectory = o3d.camera.PinholeCameraTrajectory()
param_list = trajectory.parameters
param_list.append(cam_d4150_params)
trajectory.parameters = param_list
```

**Closed** 2020-07-27 23:11 UTC
Labels: bug (possible)
