### ISSUE TITLE
Open3D 0.9 installed using pip does not work in OSX 10.14

### ISSUE THREAD

**Issue by sam598** [intel-isl/Open3D#1421] opened 2019-12-30 14:44 UTC
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/open3d/__init__.py", line 35, in <module>
    from .open3d import * # py2 py3 compatible
ImportError: dlopen(/usr/local/lib/python3.6/site-packages/open3d/open3d.cpython-36m-darwin.so, 2): Symbol not found: _objc_opt_class
  Referenced from: /usr/local/lib/python3.6/site-packages/open3d/open3d.cpython-36m-darwin.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib
 in /usr/local/lib/python3.6/site-packages/open3d/open3d.cpython-36m-darwin.so
```

**Comment by ivorycirrus** [comment] 2020-01-06 07:56
I have same issue in MacOS 10.13. This was also issued on #1412

**Comment by sromberg** [comment] 2020-01-08 21:40
I have the same issue on macOS 10.14.

**Comment by shoefer** [comment] 2020-01-09 18:17
I have the same issue both on MacOS 10.13 and 10.14.

**Comment by bfouts-kindred** [comment] 2020-01-09 20:24
I'm in the same boat

**Comment by bfouts-kindred** [comment] 2020-01-09 20:55
Seems like an issue with the latest build (from last month)
Installing an older version fixed the issue

`pip install open3d==0.8.0`

**Comment by sam598** [comment] 2020-01-09 22:55
@bfouts-kindred you can also build from source to get version 0.9.

The issue of the default pip installation of 0.9 not working on OSX 10.13 and 10.14 still needs to be fixed.

**Comment by hcoohb** [comment] 2020-01-14 23:50
It seems this issue is not just restricted to OSX ...
I am on Win10 64b, trying to use version 0.9.0 from a virtualenv gives me:
```
Traceback (most recent call last):
  File "c:/Users/.../kinect-trials/load_pickle-3d.py", line 5, in <module>
    import open3d as o3d
  File "C:\...\kinect-trials\.venv\lib\site-packages\open3d\__init__.py", line 35, in <module>
    from .open3d import * # py2 py3 compatible
ImportError: DLL load failed: The specified module could not be found.
```
version 0.8.0 does not have this issue

**Comment by syncle** [comment] 2020-02-28 16:01
Please check [discussions in here](https://github.com/intel-isl/Open3D/issues/1487#issuecomment-592416175). In short, the reported issue is not reproducible with up-to-date python env and open3d package. Closing issue.

**Closed by syncle** 2020-02-28 16:01 UTC
Labels: bug

**Comment by sam598** [comment] 2020-02-28 16:19
Hi syncle, I don't see anything in that thread about OSX 10.14.

I updated to the latest version of python (3.6.5 to 3.8.2) and now I am getting this error when installing with pip:
```
ERROR: Could not find a version that satisfies the requirement open3d (from versions: none)
ERROR: No matching distribution found for open3d
```

Can you please elaborate how to get Open3D working in OSX or explain what your solution is. Thank you.

**Comment by sam598** [comment] 2020-03-08 03:17
@syncle any update on fixing this? Let me know if you need me to post a new issue. Thanks.

**Comment by hgrabows** [comment] 2020-04-04 21:30
Using OSX 10.14.6: 
   conda install -c open3d-admin open3d 
produces the same error:
File "<string>", line 1, in <module>
...
Referenced from: /Users/me/anaconda3/lib/python3.7/site-packages/open3d/open3d.cpython-37m-darwin.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib
 in /Users/me/anaconda3/lib/python3.7/site-packages/open3d/open3d.cpython-37m-darwin.so

No idea how to fix it! It should not be a closing issue!

**Comment by maxcrous** [comment] 2020-05-06 08:25
Same issue on OS X 10.14.6

**Comment by malcatsama** [comment] 2022-11-04 10:56
I suspect the maintainers will not see any further comments here since they closed the bug.
However, in case this helps anyone, the issue does still persist and the installer should be more intelligent. **The bug is that the installer should be checking its environment more carefully.**
HOW I AVOIDED THE PROBLEM: (Macos 12.5.1, Python 3.9.13 (the last 3.9 with an installer for Macos)
python3 -m pip install open3d==0.15.1
The above works. At the time I did this, 0.16.0 was the latest open3d version and after installing that, running my python script gave me the missing symbol error. Uninstalling and then installing 0.15.1 fixed the problem for me.

  File "/Users/malcsouter/bin/pcdbin2ascii.py", line 6, in <module>
    import open3d as o3d
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/open3d/__init__.py", line 97, in <module>
    from open3d.cpu.pybind import (camera, data, geometry, io, pipelines,
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/open3d/cpu/pybind.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace (_quadmath_snprintf)

**Comment by WuxiGuy** [comment] 2022-11-05 08:36
> I suspect the maintainers will not see any further comments here since they closed the bug. However, in case this helps anyone, the issue does still persist and the installer should be more intelligent. **The bug is that the installer should be checking its environment more carefully.** HOW I AVOIDED THE PROBLEM: (Macos 12.5.1, Python 3.9.13 (the last 3.9 with an installer for Macos) python3 -m pip install open3d==0.15.1 The above works. At the time I did this, 0.16.0 was the latest open3d version and after installing that, running my python script gave me the missing symbol error. Uninstalling and then installing 0.15.1 fixed the problem for me.
> 
> File "/Users/malcsouter/bin/pcdbin2ascii.py", line 6, in import open3d as o3d File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/open3d/**init**.py", line 97, in from open3d.cpu.pybind import (camera, data, geometry, io, pipelines, ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/open3d/cpu/pybind.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace (_quadmath_snprintf)

Hi, when I try to install the version(0.15.1), it shows:
ERROR: Could not find a version that satisfies the requirement open3d==0.15.1 (from versions: 0.16.0)
ERROR: No matching distribution found for open3d==0.15.1

Do you have any idea about it?

**Comment by malcatsama** [comment] 2022-11-07 10:21
That is a puzzle!!
What I see is this:
bvy8_lidar_video/pcd_egs %  python3 -m pip install open3d==0.15.0
ERROR: Could not find a version that satisfies the requirement open3d==0.15.0 (from versions: 0.14.1, 0.15.1, 0.16.0)
ERROR: No matching distribution found for open3d==0.15.0
bvy8_lidar_video/pcd_egs %  python3 -m pip install open3d==0.15.1
Collecting open3d==0.15.1
  Downloading open3d-0.15.1-cp39-cp39-macosx_11_0_arm64.whl (91.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.5/91.5 MB 1.0 MB/s eta 0:00:00
Requirement already satisfied: setuptools>=40.8.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from open3d==0.15.1) (58.1.0)
Requirement already satisfied: numpy>=1.18.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from open3d==0.15.1) (1.23.4)
Collecting wheel>=0.36.0
  Downloading wheel-0.38.1-py3-none-any.whl (35 kB)
Installing collected packages: wheel, open3d
Successfully installed open3d-0.15.1 wheel-0.38.1

**Comment by malcatsama** [comment] 2022-11-07 10:43
All I can say is that PIP must be looking in a different place for it's packages. Try finding out where. Good luck!

**Comment by Suraj-Bhor** [comment] 2022-11-28 10:57
Had the same issue with the latest version of open3d(0.16.0)
But `pip install open3d==0.14.1` works on OSX 13.0

**Comment by WuxiGuy** [comment] 2022-11-28 15:27
> 

Thank you for your advice. I finally got open3d installed by checking the installation path of python and pip. All of these staffs should be under PATH (my laptop is Macbook with apple silicon)

**Comment by Kin-Zhang** [comment] 2023-01-24 21:58
0.15.1 also works..

0.16.0 MacOS 13.0.1 error:
```bash
Traceback (most recent call last):
  File "/Users/kinzhang/Code/edomap/main_rushversion.py", line 8, in <module>
    import open3d as o3d
  File "/Users/kinzhang/Library/Python/3.9/lib/python/site-packages/open3d/__init__.py", line 97, in <module>
    from open3d.cpu.pybind import (camera, data, geometry, io, pipelines,
ImportError: dlopen(/Users/kinzhang/Library/Python/3.9/lib/python/site-packages/open3d/cpu/pybind.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_quadmath_snprintf'
```
