### ISSUE TITLE
global registration issue

### ISSUE THREAD

**Issue by rnunziata** [intel-isl/Open3D#797] opened 2019-01-26 03:34 UTC
I have a simalar issue as Integration Issue #633.
I tried to run against the standford burghers, I limit it to the first 4000 images. 
If I run setting   
       "n_frames_per_fragment": 1000
then it works and give me a final integrated image.

if I run setting 
       "n_frames_per_fragment": 100 ( as is the default)
then the resulting integrated image is garbage.

I am not sure why setting the frames per fragment should have this effect.

I tried this both ways for the complete burghers image dataset and it results in garbage regardless weather it is 100 or 1000.

There seems to be something wrong global integration.

This error can be reproduced by using the first 4000 images of the dataset and run with frames per fragment for 100 and then again for 1000.

Below is an image opened in Meshlab that show the result of the whole burghers dataset run with frams per fragment set to 1000.

   
![screenshot from 2019-01-25 22-25-12](https://user-images.githubusercontent.com/5377074/51790263-a1677600-2160-11e9-95f6-167524eab396.png)

**Comment by syncle** [comment] 2019-01-28 19:33
Umm I think something went wrong. The Standford Burghers example should look like #598. 
Here are some questions:
- Can you tell me what is the environment for your case? 
I have tested the Reconstruction pipeline using Mac and Linux, so I guess the issue may arise from different environments/platforms.
- Are you using OpenCV with Open3D?
OpenCV helps to make better fragments by matching color images.
- Have you modified the pipeline for some reason? 
I guess not, but I am asking this just in case :)

**Comment by rnunziata** [comment] 2019-01-30 18:00
I was trying to see if I could get pcl pairwise_incremental_registration to work with the fragments but was unable to convert them to pcd format none of the load or conversion routines supplied by pcl work they complain about the format.

**Comment by syncle** [comment] 2019-01-30 19:47
@rnunziata Could you answer my previous questions? The reconstruction system was tested to produce good results on Stanford Burgher dataset. I can help you if we can simulate your environment.

**Comment by rnunziata** [comment] 2019-01-30 21:54
I am using Ubuntu16.04 with opencv 3.0 installed and working under python3 verified with Open3D. I have not modified the pipeline. 
  json file:
```
{
    "name": "Open3D reconstruction tutorial http://open3d.org/docs/tutorial/ReconstructionSystem/system_overview.html",
    "path_dataset": "dataset/stanford/burghers/",
    "path_intrinsic": "/home/rjn/Open3D/examples/TestData/camera_standford.json",
    "max_depth": 3.0,
    "min_depth": 0.3,
    "voxel_size": 0.05,
    "max_depth_diff": 0.07,
    "preference_loop_closure_odometry": 0.1,
    "preference_loop_closure_registration": 5.0,
    "tsdf_cubic_size": 3.0,
    "icp_method": "color",
    "global_registration": "ransac",
    "python_multi_threading": true,
    "n_frames_per_fragment": 100
}
```
my run file;

```

python3 run_system.py  --make config/stanford/burghers.json;
python3 run_system.py  --register config/stanford/burghers.json;
python3 run_system.py  --refine config/stanford/burghers.json;
python3 run_system.py  --integrate config/stanford/burghers.json
```
individual fragments look find in meshlab but the intergrated ply is as follows:


![snapshot00](https://user-images.githubusercontent.com/5377074/52015304-abb2a880-24af-11e9-8de9-5a2c008e8f99.png)

**Comment by syncle** [comment] 2019-01-31 06:59
I cannot reproduce the result - I also tried the same dataset with the first 5000 frames using Ubuntu 16.04. I got the following result.
![screenshot from 2019-01-30 22-52-56](https://user-images.githubusercontent.com/18297113/52036744-6cea1600-24e2-11e9-9879-48a2551a2ad2.png)

**Comment by rnunziata** [comment] 2019-01-31 18:39
I was able to get this to work if I set the n_fraims to 1000. The image I get is different form yours and seem to cover more ground. I used the download script supplied is it possible the data has changed?
![snapshot01](https://user-images.githubusercontent.com/5377074/52076814-7f556580-255d-11e9-9bde-f2b80480635b.png)

**Comment by syncle** [comment] 2019-02-01 05:33
I used the first 5000 frames as you mentioned. I used the script provided in the Reconstruction system to download the dataset. 

@rnunziata We are not being synchronized. Please help us to find the root cause - it is hard for me to figure out what is happening if you keep trying your own configuration. As I mentioned earlier, I recommend 100 frames per fragment, and use OpenCV together.

It is necessary to find what is breaking in your case (RGBDOdometry or Global registration), so that I can help with you. [Here](https://github.com/IntelVCL/Open3D/issues/797#issuecomment-459124779) you mentioned all  frames looks good, but [here](https://github.com/IntelVCL/Open3D/issues/797#issuecomment-459135133) you mentioned fragment 9 is breaking. If RGBD frame registration is breaking, it is necessary to understand what makes the break and why it happens in your Ubuntu system and why it is not happening my Ubuntu system. 

Can you go back to the pure Reconstruction system, stash custom changes, and reproduce the issue, and analyze the fragments again? This is the only way I want to request because I cannot produce the issue from my side.

**Comment by rnunziata** [comment] 2019-02-01 17:11
I deleted all references to Open3D and have installed it using pip3 install python-open3d 
I downloaded the source examples reconstruction run_system.py  and running from that ... will update here when done.

**Comment by syncle** [comment] 2019-02-09 05:10
Could you see every fragments are look fine? You can quickly do this with this command
```
cd Open3D/examples/Python/ReconstructionSystem
python debug/visualize_fragments.py config/stanford/burghers.json
```
If so, could you try pairwise point cloud alignment using debug mode something like 
```
python debug/pairwise_pc_alignment.py config/stanford/burghers.json 0 1
```
This aligns pcd 0 and 1. You can try [1, 2], [2, 3], [3, 4] ... to find what is breaking. If you find the breaking pair, it would be good for us to understand what pair is making issue.

**Comment by rnunziata** [comment] 2019-02-09 19:59
I did this and all pair wise registrations look good...even though the scene does not.

**Comment by syncle** [comment] 2019-02-11 01:19
Oh, I see. Based on your description, in your environment, fragment 6 is not good after the integration, right? Since I cannot produce the result (as shown above, my fragment 6 looks fine), I still need your help. 

Could you identify what frames being broken? there is ``python debug/pairwise_rgbd_alignment.py`` you can try, or you can compare pose graph before and after the optimization. For example, the easiest way is to read the pose graph and visualize camera centers by using ``inverse(camera extrinsic) * [0,0,0,1]``. There must be some jump in the camera sequences that makes the ugly artifact in your case. 

Then, we can identify whether the issue comes from RGBDOdometry or PoseGraphOptimization and what specific code makes differences. 

I appreciate what you are sharing for me @rnunziata. ;)

**Comment by rnunziata** [comment] 2019-02-11 20:14
So I was printing only at fragment level so I reran an printed at frame level for the integration. On fragment 8 frame 0 I get:

![snapshotthisone00](https://user-images.githubusercontent.com/5377074/52590476-5fe8f300-2e0f-11e9-8667-a3d0ab54776c.png)


The image for frag 8 frame 0 is rdgd  800

![000800](https://user-images.githubusercontent.com/5377074/52590046-5c08a100-2e0e-11e9-97a2-7b8bd1af0472.png)


The pair wise rgbd for the image rgbd pair 799 and 800 return the following:


![screenshot from 2019-02-11 14-58-16](https://user-images.githubusercontent.com/5377074/52590339-0ed8ff00-2e0f-11e9-924c-febdfed1a8ee.png)




surrounding frames (images) all look the same even within fragment 7 set.  So the error seems only to occur at the boundary between fragments. I can see no difference in the surrounding images.

**Comment by syncle** [comment] 2019-02-12 22:44
So you mean there is a jump between fragments when it is being used for scene integration, right? I am suspecting there is a possible reason for this. 

-----

Can you try the following

1) uninstall Open3D python package (depending on how you install, use ``pip uninstall open3d`` or ``conda uninstall open3d``
1-1) make sure open3d was completely removed in your system. ``python -c "import open3d"`` should be failed because there is no open3d now.
2) remove Open3D folder.
3) change to your working directory and do ``git clone --recursive https://github.com/IntelVCL/Open3D.git``
4) ``cd Open3d``
5) open ``CMakeLists.txt`` and change ``ON`` to ``OFF`` in the following line
```
option(WITH_OPENMP               "Use OpenMP multi-threading"               ON)
```
6) ``mkdir build``
7) ``make -j && make install-pip-package``
8) download the dataset again and run the reconstruction system again.

-----

This will remove open3d from your system and install a new clean version with OpenMP flag OFF. 

I received some user report that RANSAC registration induces unexpected registration result if OpenMP and ``joblib`` in Python is used together. Therefore, I am recommending you to try Open3D ReconstructionSystem without OpenMP.

**Comment by rnunziata** [comment] 2019-02-13 18:03
On the last part the:
` make install-pip-package`

I get at end:
`open3d-0.5.0.0-cp35-cp35m-linux_x86_64.whl is not a supported wheel on this platform`.

Also I was wondering if I need to pip install open3d-python
After install with the error above 
I tried to do a python3; import open3d and get module not found.

**Comment by syncle** [comment] 2019-02-13 18:18
The error message says .whl is not compatible with your default Python version. You will need to use virtual env - consider using conda, and make a new env for Open3D before build from source.

**Comment by rnunziata** [comment] 2019-02-13 18:21
Ok...I will post here when that is done. I may not get to it today. thank you.

**Comment by syncle** [comment] 2019-02-15 06:50
can you do ``conda activate Open3D`` and ``rm build && mkdir build && cd build && cmake ..``? I think build folder is still using old cmakecash.

**Comment by rnunziata** [comment] 2019-02-15 15:25
this worked....but do make-install-pip-package or a make install after this?

**Comment by syncle** [comment] 2019-02-15 16:04
This will help. More information can be found from [here](http://open3d.org/docs/compilation.html#ubuntu): 
```
make -j && make install-pip-package
```

**Comment by rnunziata** [comment] 2019-02-15 19:58
yeah....it worked for whole burghes dataset. Thank you so much. :-)

![snapshotdone00](https://user-images.githubusercontent.com/5377074/52881228-0b58b700-3132-11e9-8177-b262cc0962f0.png)

**Comment by syncle** [comment] 2019-02-15 20:08
Awesome! Now I can see what makes an issue using OpenMP + Python ``joblib`` together in the ReconstructionSystem is making some issues. I will open another issue for this.

**Comment by syncle** [comment] 2019-02-16 18:23
Opened a new issue with problem specific description. The discussion will be continued there. Thanks for the bug report @rnunziata - closing this thread.

**Comment by ghoshaw** [comment] 2019-06-10 11:49
I tried as above to use conda, but still get at end:
open3d-0.5.0.0-cp35-cp35m-linux_x86_64.whl is not a supported wheel on this platform.

**Comment by qianyizh** [comment] 2019-06-14 07:40
@yxlao take a look at the conda whl problem? ^

**Comment by yxlao** [comment] 2019-09-16 15:22
@ghoshaw please check the Python and OS version when installing `.whl` package in conda.

**Comment by DmytroKushnirSoftserveinc** [comment] 2019-10-01 13:12
I had this issue reproduced on my own collected dataset using version 0.8.0. I suppose that the order of fragments matching suffers due too race condition. 
Using flag '--debug_mode' for reconstruction resulted in the flawless results.  Thou I supposed that there is some race condition causing it.

However, what is confusing: using "python_multirhreading" = false, results only in a slowdown of reconstruction, but misalignment remains. 

Note: Used data is polluted with plenty of registration artifacts, which could contribute to reconstruction failure.

If outliers are cleaned-up, even the basic multithread CPU-based version produces stable reconstruction results.

**Comment by MaxChanger** [comment] 2019-10-24 03:08
@DmytroKushnirSoftserveinc Hello, I probably have a similar problem with version 0.8.0. Before I used our own dataset, I did some tests in the tutorial dataset (redwood), but there have been many bad results, for example:
![](https://user-images.githubusercontent.com/35401968/67393896-e0363980-f5d5-11e9-8288-10f27a769b10.png)

> Thou I supposed that there is some **race condition** causing it.

What you mentioned above, I want to know what you mean by **"race condition"**, thanks.

**Comment by germanros1987** [comment] 2020-07-27 23:27
Issue closed due to lack of activity. Feel free to open a new issue if you still consider this is a critical matter.

**Closed by germanros1987** 2020-07-27 23:27 UTC
Labels: question
