### ISSUE TITLE
Display 2D image

### ISSUE THREAD

**Issue by Zumbalamambo** [intel-isl/Open3D#2961] opened 2021-01-28 22:59 UTC
Please provide an option to display the 2D image in some corner of the visualizer

**Comment by ssheorey** [comment] 2021-02-01 23:24
Is this what you are looking for?
[O3DVisualizer background image](http://www.open3d.org/docs/latest/python_api/open3d.visualization.O3DVisualizer.html?highlight=background#open3d.visualization.O3DVisualizer.set_background)
[Open3DScene background image](http://www.open3d.org/docs/latest/python_api/open3d.visualization.rendering.Open3DScene.html?highlight=background#open3d.visualization.rendering.Open3DScene.set_background)

**Comment by Zumbalamambo** [comment] 2021-02-01 23:49
@ssheorey no... I'm looking for an option to show an image in some specific location just like how buttons or text boxes are shown. Just like a canvas.

**Comment by prewettg** [comment] 2021-02-02 00:43
You are looking for a UI element? If so, [gui::ImageLabel](https://github.com/intel-isl/Open3D/blob/master/cpp/open3d/visualization/gui/ImageLabel.h) will let you do that. (Also, `gui::Button` has a constructor that will let you pass an image.) You can see an example in [`examples/python/gui/all-widgets.py`](https://github.com/intel-isl/Open3D/blob/8425fa353b2a1ec7a562a368541501fa083bd620/examples/python/gui/all-widgets.py#L116).

**Comment by Zumbalamambo** [comment] 2021-02-02 02:28
I tried that option but it won't let me to dynamically update the image :(

**Comment by prewettg** [comment] 2021-02-02 05:41
Yes, ImageLabel is assuming that the image is constant (like an icon). We do not have the ability to change the image at the moment, and if you are really wanting a movie widget, we definitely to do not have that (although we will be working on a movie widget soon).

**Comment by ssheorey** [comment] 2021-02-02 16:53
This is a duplicate of issue #2886

**Comment by ssheorey** [comment] 2021-03-13 20:03
Duplicate of #2886

**Comment by prewettg** [comment] 2021-03-19 20:15
As noted above, #3002 will close this. Please see the `examples/python/gui/video.py` that will be added for an example of how to update the image.

**Closed** 2021-04-05 21:07 UTC
Labels: feature request, visualization

**Comment by julienguegan** [comment] 2021-07-27 13:29
@prewettg I am trying to run **examples/python/gui/all-widgets.py** and it seems that `module 'open3d.visualization.gui' has no attribute 'ImageLabel'` ... I am using the latest release : 0.13.0

Do you have an idea what have changed ? How to correct this error ?

**Comment by Kin-Zhang** [comment] 2023-01-13 20:44
update the example here:
1. code linke: https://github.com/isl-org/Open3D/blob/73508bcaba0a9a31e398bf8de76e3bbeaed81540/examples/python/visualization/video.py
2. open3d version must >=0.15.1, [reference link](https://stackoverflow.com/questions/71367061/attribute-error-module-open3d-has-no-attribute-data)

Example Video:

https://user-images.githubusercontent.com/35365764/212415757-929e94b8-4671-418a-b4ae-21ef2bf75ade.mp4
