### ISSUE TITLE
erroneous behavior with multiple open visualizer windows (python)

### ISSUE THREAD

**Issue by cmatija** [intel-isl/Open3D#1917] opened 2020-06-02 08:23 UTC
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
I have 2 windows open, each displaying 3D point clouds. You can think of the first window as showing the whole, global point cloud, whereas the second one shows a small part of it and allows for points to be selected (``open3d.visualization.VisualizerWithEditing``). Upon calling destroy_window() on the second window, the first one gets closed as well, which should not happen.

**To Reproduce**
```
# pcds = [[pcd_local_1, pcd_local_2, ..., pcd_local_n], pcd_global], all separate PointCloud objects, in my case:
# [[geometry::PointCloud with 2150 points.,
#  geometry::PointCloud with 2058 points.,
#  geometry::PointCloud with 2040 points.,
#  geometry::PointCloud with 2083 points.,
#  geometry::PointCloud with 7143 points.],
# geometry::PointCloud with 75634 points.]
vis_global = open3d.visualization.Visualizer()
vis_global.create_window(width=600, height=600)
vis_global.add_geometry(pcds[1])
vis_global.poll_events()
pts = []
for i, pc in enumerate(pcds[0]):
    vis = open3d.visualization.VisualizerWithEditing()
    vis.create_window(width=600, height=600)
    vis.add_geometry(pc)
    vis.poll_events()
    vis.run() # after selecting some points, press q
    vis.destroy_window()
    pts += [vis.get_picked_points()]
```

**Expected behavior**
In each loop iteration, the window corresponding to ``vis`` gets closed, whereas the window for ``vis_global`` remains open.  

**Environment (please complete the following information):**

- Operating system: Arch Linux,  5.6.15-arch1-1
- Python version: Python 3.7.6
- Open3D version: 0.10.0
- Is this remote workstation?: no
- How did you install Open3D?: pip inside conda, but same thing happens when using ``conda install -c open3d-admin open3d``

**Additional context**
The number of loop iterations until ``vis_global`` is destroyed varies. It sometimes survives the first iteration of above loop, but then gets destroyed in the second.

**Comment by MaxChanger** [comment] 2020-09-08 06:59
What this function `vis.run()` does is to activate the window. This function will block the current thread until the window is closed, as shown in [link](http://www.open3d.org/docs/release/python_api/open3d.visualization.Visualizer.html?highlight=vis%20run#open3d.visualization.Visualizer.run).
But there is no `vis_global.run()` in your code, in my test, when there is only one window, not adding .run() will cause it to appear suddenly and then disappear, could use the following code to reproduce
```python
pcd_local_1 = o3d.io.read_point_cloud('the path of pcd file')
vis_1 = o3d.visualization.Visualizer()
vis_1.create_window(window_name="left", width=600, height=600)
vis_1.add_geometry(pcd_local_1)
vis_1.poll_events()
# vis_1.run()
# vis_1.destroy_window()
```
And then, if I use the following code, two windows will appear at the same time (why `vis_1` is activated ??), but the left window of `vis_1` cannot accept any keyboard and mouse responses. When closing vis_2, vis_1 will also be closed.

```python
vis_1 = o3d.visualization.Visualizer()
vis_1.create_window(window_name="left", width=600, height=600)
vis_1.add_geometry(pcd_local_1)
vis_1.poll_events()
# vis_1.run()
# vis_1.destroy_window()

vis_2 = o3d.visualization.Visualizer()
vis_2.create_window(window_name="right", width=600, height=600, left=800)
vis_2.add_geometry(pcd_local_2)
vis_2.poll_events()
vis_2.run()
# vis_2.destroy_window()
```

There is no `vis_global.run()` operation in your code, according to my above guess, this window can be activated by `vis.run()`, and I don’t think your `vis_global viewport`  can do any operation (rotation or zoom). Am I right？ @cmatija @griegler

**Comment by prewettg** [comment] 2021-03-19 21:56
Closing since no activity for six months, and concerns the old visualizer, which is now deprecated. We do have a multiple window example for the new GUI:  [`examples/python/gui/multiple-windows.py`](https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/multiple-windows.py)

**Closed by prewettg** 2021-03-19 21:56 UTC
Labels: possible bug

**Comment by TheTomer** [comment] 2022-06-15 17:23
> 
I've encountered the same problem as the OP, but the link you've provided directs to a non-existent page and I can't seem to find that page using Google. Can you please re-post the link?

Btw I'm working with Open3D 0.9.0 and would love to find a way to prevent the second window from destroying the first (main) window. Did anyone find a solution for that?
