### ISSUE TITLE
Segmentation fault: 11 on MacOS Mojave 10.14.6

### ISSUE THREAD

**Issue by ppkettu** [intel-isl/Open3D#2598] opened 2020-11-10 14:39 UTC
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**

Segmentation fault: 11 on MacOS Mojave 10.14.6.

**To Reproduce**

1. cd Open3D/python/examples/python

Saved this
`import open3d as o3d

print("Load a ply point cloud, print it, and render it")
pcd = o3d.io.read_point_cloud("../test_data/fragment.ply")
print(pcd)

o3d.visualization.draw_geometries([pcd],
                                  zoom=0.3412,
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[2.6172, 2.0475, 1.532],
                                  up=[-0.0694, -0.9768, 0.2024])`
under name visu-poclo.py.

2. python visu-poclo.py

3. See error
`Load a ply point cloud, print it, and render it
PointCloud with 196133 points.
Segmentation fault: 11`

**Expected behavior**
Point cloud rendering window.

**Screenshots**

**Environment (please complete the following information):**

- Operating system: MacOS Mojave 10.14.6.
- Python version: 3.8.3
- Open3D version: open3d-0.11.2
- Is this remote workstation?:  no
- How did you install Open3D?: 
conda install -c open3d-admin open3d
conda install -c conda-forge addict
conda install -c conda-forge plyfile

- Compiler version (if built from source): (e.g. gcc 7.5, clang 7.0)

**Additional context**

Tried on two Macs.
C++ programs, like Open3D.app work fine.

**Comment by prewettg** [comment] 2020-11-11 03:06
I can reproduce this problem, and it appears to be a problem with sharing OpenGL with Filament, since we crash in an OpenGL call with the instruction pointer at 0x0. As a workaround, you can compile with the cmake flag `-DBUILD_GUI=OFF` and it will work.

**Comment by ZJC1013** [comment] 2020-12-18 07:01
> I can reproduce this problem, and it appears to be a problem with sharing OpenGL with Filament, since we crash in an OpenGL call with the instruction pointer at 0x0. As a workaround, you can compile with the cmake flag `-DBUILD_GUI=OFF` and it will work.

Thank you for proving this workaround! This works on MacOS. But certainly hope this can be resolved in the future release.

**Closed** 2020-12-22 18:00 UTC
Labels: possible bug
