### ISSUE TITLE
Crash - free(): invalid pointer while importing Open3D after PyTorch

### ISSUE THREAD

**Issue by mcarletti** [intel-isl/Open3D#1207] opened 2019-09-26 10:29 UTC
When I import Open3D after PyTorch, I get an invalid pointer error then Python crashes.
I solved the issue by inverting the import order but I don't get why this happens.
What could it be?
Thanks.

```
Python 3.5.3 (default, May 18 2017, 14:40:48) 
[GCC 5.4.1 20161019] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import open3d
free(): invalid pointer
Aborted (core dumped)
```

**Environment:**
 - OS: Ubuntu 18.04
 - Python version: 3.5.3
 - Open3D version: 0.8.0.0
 - Is this remote workstation?: no
 - How did you install Open3D?: (see later)

**Additional context**
This specific version of Python is the embedded interpreter of [Blender 2.79b](https://download.blender.org/release/Blender2.79/), which is installed in ```/opt/blender-2.79b-linux-glibc219-x86_64```.
In order to install the packages I ran the following commands:
```
cd /opt/blender-2.79b-linux-glibc219-x86_64
./2.79/python/bin/python3.5m 2.79/python/lib/python3.5/ensurepip
./2.79/python/bin/pip3.5 install open3d torch
```

**Comment by griegler** [comment] 2019-09-26 11:03
Duplicate of #922

**Closed by griegler** 2019-09-26 11:03 UTC
Labels: bug
