### ISSUE TITLE
Colored point cloud registration fail to achieve local best solution and a possible solution.

### ISSUE THREAD

**Issue by lvgeng** [intel-isl/Open3D#1297] opened 2019-11-03 21:36 UTC
Colored point cloud registration is a really amazing feature of open3d...
http://www.open3d.org/docs/release/tutorial/Advanced/colored_pointcloud_registration.html

There is a similar problem. As mentioned, the point clouds fly away.
I checked the objective function and I think it is certainly a bug in this case.....

A wild guess is that the optimiser used in the registration have a larger step than expected.
When the first guess is made, there is a possibility that the two point cloud has zero corresponding  point pairs so that the objective function gives zero, which is considered to be a "better" solution than others. It might happen to a lot of situation, especially when the point clouds are relatively small and have few points.

https://github.com/intel-isl/Open3D/issues/362

However I have some issue while playing with my own data. The init transformation should be good enough I guess... The color difference is added in the visualization stage, it should not affect the colored point cloud registration.

My testing code and data
[python_script_and_data.zip](https://github.com/intel-isl/Open3D/files/3752698/python_script_and_data.zip)

and results. (each one use the previous result as the initial pose)
original:
![Screenshot from 2019-10-21 21-12-32](https://user-images.githubusercontent.com/9252650/67239714-bb13c080-f447-11e9-9206-6b9611c42b23.png)
point to point 
![Screenshot from 2019-10-21 21-12-44](https://user-images.githubusercontent.com/9252650/67239741-c830af80-f447-11e9-849d-acb8ff3f24a2.png)
point to plane
![Screenshot from 2019-10-21 21-12-55](https://user-images.githubusercontent.com/9252650/67239764-d4b50800-f447-11e9-8f8d-a6b9747ddde3.png)
registration_colored_icp
![Screenshot from 2019-10-21 21-13-15](https://user-images.githubusercontent.com/9252650/67239789-e696ab00-f447-11e9-8b4f-a6d5c2574f88.png)

I understand that it is possible to have a bad result if the data is not so good, but I cannot understand why it pushes the point cloud away after the registration. Is there any solution for that?

My data is here. They are point cloud I generated by other methods.

And the function

`        result_icp = o3d.registration.registration_colored_icp(
            source_down, target_down, radius, current_transformation,
            o3d.registration.ICPConvergenceCriteria(relative_fitness=1e-6,
                                                    relative_rmse=1e-6,
                                                    max_iteration=iter))`
should I change the relative_fitness or relative_rmse?
And ... what do they do exactly?

**Comment by syncle** [comment] 2019-11-05 16:53
Duplicate of #1261. Please check out [this](https://github.com/intel-isl/Open3D/issues/1261#issuecomment-549909729)

**Comment by lvgeng** [comment] 2019-11-05 21:42
Checked. Unfortunately I have already tried that... the details are in that issue.
> Duplicate of #1261. Please check out [this](https://github.com/intel-isl/Open3D/issues/1261#issuecomment-549909729)

**Comment by argosvr** [comment] 2019-11-17 22:58
yes.. without a working ransac or other icp registration, colored point cloud registration makes pointclouds flying away...

**Comment by lvgeng** [comment] 2019-11-25 16:22
> yes.. without a working ransac or other icp registration, colored point cloud registration makes pointclouds flying away...

However... the problem is, when we are using  colored point cloud registration, it means the ICP does not work well.

**Comment by germanros1987** [comment] 2020-08-07 04:48
@lvgeng I agree. We definitely need to work on a new registration method/an upgrade of ICP. We will keep you posted

**Comment by szx0112** [comment] 2020-08-12 17:14
Colored ICP is a necessary step for many reconstruction applications where the geometric difference between RGBD frames are not significant, along walls, inside a tunnel. Under such cases, the color information is the major source to guide the registration.

I think the flying away issue arise when we keep reducing the scale for finer registration. My workaround is to break the registration at certain scale when the fitness/inlier_rmse is smaller/larger than the previous iteration. This can prevent the registration diverge but since we break the registration at larger scale,we may not able to get the expected level of accuracy. 

I really appreciate if someone can work on this and further improve the current colored ICP implementation in open3d.

**Comment by theNded** [comment] 2020-08-20 17:37
According to my experience, Colored ICP will face numerical issues when the structure is very simple, like this or planar cases. We need to investigate that part and eliminate unreliable color gradients.

**Closed by theNded** 2020-08-20 17:37 UTC
Labels: bug (possible)
