### ISSUE TITLE
How could i  set line width in rendered scene???

### ISSUE THREAD

**Issue by JianqiangDing** [intel-isl/Open3D#2651] opened 2020-11-22 11:20 UTC
https://github.com/intel-isl/Open3D/blob/414a67ae5111b352c20511b0d611fdd9cf163177/cpp/pybind/visualization/rendering/rendering.cpp#L102

I can change the point size by updating the point_size in Material, How could I change the line width??? I didn't find the right API? does the API exist? Any suggestion would be helpful. thanks

**Comment by prewettg** [comment] 2021-03-20 00:46
I don't think we had line widths implemented when you opened the issue, but they are implemented now, and should be in 0.12. I just added an example in #3194 (`examples/python/gui/line-width.py`), which I reproduce here since it has not been merged yet:
```
#!/usr/bin/env python
import open3d as o3d
import random

NUM_LINES = 10

def random_point():
    return [5 * random.random(), 5 * random.random(), 5 * random.random()]

def main():
    pts = [random_point() for _ in range(0, 2 * NUM_LINES)]
    line_indices = [[2 * i, 2 * i + 1] for i in range(0, NUM_LINES)]
    colors = [[0.0, 0.0, 0.0] for _ in range(0, NUM_LINES)]

    lines = o3d.geometry.LineSet()
    lines.points = o3d.utility.Vector3dVector(pts)
    lines.lines = o3d.utility.Vector2iVector(line_indices)
    # The default color of the lines is white, which will be invisible on the
    # default white background. So we either need to set the color of the lines
    # or the base_color of the material.
    lines.colors = o3d.utility.Vector3dVector(colors)

    # Some platforms do not require OpenGL implementations to support wide lines,
    # so the renderer requires a custom shader to implement this: "unlitLine".
    # The line_width field is only used by this shader; all other shaders ignore it
    mat = o3d.visualization.rendering.Material()
    mat.shader = "unlitLine"
    mat.line_width = 10  # note that this is scaled with respect to pixels,
    # so will give different results depending on the
    # scaling values of your system
    o3d.visualization.draw({
        "name": "lines",
        "geometry": lines,
        "material": mat
    })

if __name__ == "__main__":
    main()
```

**Closed by prewettg** 2021-03-20 00:46 UTC
