### ISSUE TITLE
request text for display in visualization with python

### ISSUE THREAD

**Issue by yzl96** [intel-isl/Open3D#1157] opened 2019-09-04 01:52 UTC
Hi, I want to display text in visualization.
the solution I can get is two: 1.set position (x,y,z), and use a function to display the text in the position. 2. because I want to display text in bounding box, so just add a parameter(text) to open3d.geometry.LineSet().

**Comment by syncle** [comment] 2019-10-05 17:25
Sorry, @yzl96. This request has not been addressed [for a long time](https://github.com/intel-isl/Open3D/issues/2). We are considering large update on the visualization module to provide the requested feature.

**Comment by hcoohb** [comment] 2020-01-19 12:04
Definitely a wanted feature by many of us!

Duplicate of #2 ?

**Comment by syncle** [comment] 2020-02-27 13:03
Please check out [this suggestion.](https://github.com/intel-isl/Open3D/issues/2#issuecomment-549615014)

**Comment by germanros1987** [comment] 2020-08-07 03:49
We haven't forgotten about this. It will happen. In fact, part of this is already out as part of the new GUI module and the python API for the GUI module, but displaying text in the Render widget is still not possible.

**Comment by germanros1987** [comment] 2020-11-02 23:49
Still working on this for 0.12

**Comment by Physu** [comment] 2021-01-14 09:29
Hope can add display text function soon. Thanks for your extraordinary work!

**Comment by JianqiangDing** [comment] 2021-03-10 06:47
still waiting for the release of this USEFUL feature

**Comment by luke-sockhill** [comment] 2021-03-31 12:55
This feature would be super helpful! When is it likely to be released?

**Comment by prewettg** [comment] 2021-03-31 18:07
The new GUI has this as of 0.12:
```
import numpy as np
import open3d as o3d
import open3d.visualization.gui as gui
import open3d.visualization.rendering as rendering

def make_point_cloud(npts, center, radius):
    pts = np.random.uniform(-radius, radius, size=[npts, 3]) + center
    cloud = o3d.geometry.PointCloud()
    cloud.points = o3d.utility.Vector3dVector(pts)
    colors = np.random.uniform(0.0, 1.0, size=[npts, 3])
    cloud.colors = o3d.utility.Vector3dVector(colors)

def main():
    app = gui.Application.instance
    app.initialize()

    points = make_point_cloud(100, (0, 0, 0), 1.0)

    w = app.create_window("Open3D - 3D Text", 1024, 768)
    widget3d = gui.SceneWidget()
    widget3d.scene = rendering.Open3DScene(w.renderer)
    mat = rendering.Material()
    mat.shader = "defaultUnlit"
    mat.point_size = 5 * w.scaling
    widget3d.scene.add_geometry("Points", points, mat)
    for idx in range(0, len(points.points)):
        widget3d.add_3d_label(points.points[idx], "{}".format(idx))
    bbox = widget3d.scene.bounding_box
    widget3d.setup_camera(60.0, bbox, bbox.get_center())
    w.add_child(widget3d)

    app.run()

if __name__ == "__main__:
    main()
```
#3233 also adds this to O3DVisualizer, and adds an example in `examples/python/gui/text3d.py`

**Closed by prewettg** 2021-03-31 18:07 UTC
Labels: feature request, visualization

**Comment by luke-sockhill** [comment] 2021-04-08 13:26
When trying to run the code above I get this error: 
AttributeError: 'open3d.cpu.pybind.visualization.O3DVisualizer' object has no attribute 'add_3d_label'

**Comment by TangToy** [comment] 2021-08-10 08:25
> @luke-sockhill I also had the same issue as yours when I was using o3d `v1.12`, and now I just `pip install --upgrade open3d` to `v1.13`, and problems solved. I am not sure how your o3d was installed, but it seems installation from source is not necessary now. I am using python=3.8.

Thanks, problem solved.

**Comment by satyajit-ink** [comment] 2022-06-29 12:02
For anyone having issues with the above code, here's the updated code: http://www.open3d.org/docs/release/python_example/visualization/index.html#text3d-py
