### ISSUE TITLE
OBJs with multiple materials no longer supported in 0.11?

### ISSUE THREAD

**Issue by jeffmm** [intel-isl/Open3D#2510] opened 2020-10-19 08:25 UTC
**Describe the bug**
Open3D 0.10.X was capable of loading OBJ files that had multiple materials per object. After compiling Open3D from source and installing the pip version, I've found that 0.11.0 is unable to do so.

I didn't see this in the changelog and I'm curious whether this feature was removed intentionally or why the choice was made and whether it can be easily re-implemented.

**To Reproduce**

1) Get an OBJ file with multiple material textures
2) Load the OBJ using o3d.io.read_triangle_mesh
3) Read the warning about inability to use multiple materials for the OBJ file

**Expected behavior**
o3d.io.read_triangle_mesh loads multiple material textures as in Open3D 0.10.X

**Environment (please complete the following information):**

- Operating system: OSX 10.15.7, Ubuntu 18.04.5 LTS
- Python version: Python3.7, Python3.8
- Open3D version: 0.11.0, 0.11.0+f2aec54e
- Is this remote workstation?: No
- How did you install Open3D?: pip, build from source
- Compiler version (if built from source): gcc 7.5.0

**Additional context**
The compiled version was built in a Docker container to do headless rendering (which rendered pointclouds, etc fine, but I work with OBJs unfortunately).

**Comment by jeffmm** [comment] 2020-10-19 19:11
The functionality was broken not that long ago in PR #2132. Changing one line of code restores the feature:

In `cpp/open3d/io/TriangleMeshIO.cpp`,
replace `{"obj", ReadTriangleMeshUsingASSIMP},`
with `{"obj", ReadTriangleMeshFromOBJ},`

and everything works fine when compiling on Ubuntu with headless rendering enabled (ie, I'm able to generate images of a textured mesh from an OBJ that has multiple material files).

**Comment by germanros1987** [comment] 2020-11-03 01:53
@errissa could you please look into this?

**Comment by errissa** [comment] 2020-11-03 15:38
This a duplicate of #1889. A similar issue is also reported in #1638 

I am working on fixing this.

**Comment by errissa** [comment] 2020-11-05 01:37
This is now fixed.

**Closed by errissa** 2020-11-05 01:37 UTC
Labels: feature request
