### ISSUE TITLE
Cannot change background color with vis-gui.py example

### ISSUE THREAD

**Issue by cygann** [intel-isl/Open3D#2284] opened 2020-09-03 21:04 UTC
**Describe the bug**

I'm trying to use the new GUI module for point cloud visualizations, but am having trouble with changing the background color. In the [vis-gui.py example](https://github.com/intel-isl/Open3D/blob/master/examples/python/GUI/vis-gui.py), I cannot get the background color to change at all despite selecting a new background color with the "BG Color" color picker.

I have also tried hard-coding line 135 of vis-gui.py to choose a different initial background color, which does not work either. 

**To Reproduce**

I built open3d from source today (e3f0edb65770baeb6a08225c257b124764af4e87) and ran the [vis-gui.py example](https://github.com/intel-isl/Open3D/blob/master/examples/python/GUI/vis-gui.py) with a pcd file and tried to change the background color with the "BG Color" color picker.

**Expected behavior**
Expected the background color to change.

**Screenshots**
![Screen Shot 2020-09-03 at 1 48 20 PM](https://user-images.githubusercontent.com/16779401/92165900-9e2c7580-edec-11ea-91ac-9b53145a6170.png)

**Environment (please complete the following information):**

- Operating system: OSX 10.15.6
- Python version: Python 3.7.1
- Open3D version: From source (Commit: e3f0edb65770baeb6a08225c257b124764af4e87)
- Is this remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): Apple clang 11.0.3

**Comment by prewettg** [comment] 2020-09-08 21:06
I think this was caused by moving to Filament 1.8 from 1.4.5, which changed how the background color is set, and the example didn't get updated. Fixed in #2299.

**Closed** 2020-09-09 03:29 UTC
Labels: bug (possible)

**Comment by cygann** [comment] 2020-09-09 22:08
Great, thank you!

**Comment by rajanidulal** [comment] 2020-10-01 20:47
Hello @cygann, I am trying to run vis-gui.py file. I am getting a module not found error for open3d.visualization.gui. Did you get any errors while running this py file? If so how did you solve it? I compiled the code from the source code. 

![image](https://user-images.githubusercontent.com/56923694/94861411-19d60e00-03fd-11eb-9762-06b782a96088.png)
